### ISSUE TITLE
kthread_func should have a while loop?

### ISSUE THREAD

**Issue by pranjas** [mandeepsandhu/uio-hotplug-test#1]
Looks like uio_unregister will be done if kthread_should_stop is false? I'm not well versed with uio but is this how it's supposed to be?

**Comment by mandeepsandhu** [comment]
`kthread_should_stop()` will return true, if someone's called `kthread_stop()`. This check is there simply to avoid double de-registration of uio. Imagine a scenario, where the thread has been scheduled to run, but before it does, someone removes the module (`rmmod`). In this case, when the thread callback runs, it will not do anything as `uio_unregister()` would've already been called by the module exit routine.
